    steps:
    - name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: 'bash'
      args:
        - '-c'
        - |
          if [ $BRANCH_NAME = master ]
          then
            sed -i "s/_VER_/minified/" src/app.js
            mv Dockerfile.min Dockerfile
          else
            sed -i "s/_VER_/UN minified/" src/app.js
            mv Dockerfile.nomin Dockerfile
          fi
          

    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/quickstart-image:$BRANCH_NAME-$REVISION_ID', '.' ]
      
    - name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/$PROJECT_ID/quickstart-image']
    
    - name: 'gcr.io/cloud-builders/kubectl' 
      entrypoint: 'bash' 
      args: 
        - '-c'
        - |
          sed -i "s/IMAGE_TAG/$BRANCH_NAME-$REVISION_ID/" deploy.yaml
          sed -i "s/PROJECT_ID/${PROJECT_ID}/" deploy.yaml

          export CLOUDSDK_COMPUTE_ZONE=asia-south1-a
          if [ $BRANCH_NAME = master ]
          then
            export CLOUDSDK_CONTAINER_CLUSTER=azad-test-master
          else
            export CLOUDSDK_CONTAINER_CLUSTER=azad-test-cluster
          fi
          /builder/kubectl.bash apply -f deploy.yaml