apiVersion: v1
kind: Service
metadata:
  name: hello-server2
spec:
  ports:
- port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: hello-server2
  type: LoadBalancer  

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-server2
spec:
  revisionHistoryLimit: 2
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-server2
    spec:
      containers:
- image: gcr.io/PROJECT_ID/gcptest-image:IMAGE_TAG
        imagePullPolicy: Always
        name: hello-server2
        ports:
- containerPort: 3000
        env:
        livenessProbe:
